#!/usr/bin/env bash
# Start a vLLM OpenAI-compatible server for TAHI coprocessors.
#
# The defaults below ARE the standard TAHI setup -- just run it bare:
#
#   scripts/start_vllm_server.sh
#
# Every default is overridable by flag or environment variable:
#
#   scripts/start_vllm_server.sh --model Qwen/Qwen2.5-32B-Instruct --quantization ""
#   TAHI_VLLM_MODEL=meta-llama/Llama-3.3-70B-Instruct scripts/start_vllm_server.sh
#   GPU_MEM_UTIL=0.90 scripts/start_vllm_server.sh      # vLLM owns the GPU alone

set -euo pipefail

# --- Defaults: the standard TAHI configuration -------------------------------
MODEL="${TAHI_VLLM_MODEL:-Qwen/Qwen2.5-72B-Instruct-AWQ}"
QUANTIZATION="${TAHI_VLLM_QUANTIZATION:-awq}"
PORT="${TAHI_VLLM_PORT:-8000}"
MAX_MODEL_LEN="${TAHI_VLLM_MAX_MODEL_LEN:-8192}"
TP_SIZE="${TAHI_VLLM_TP_SIZE:-1}"
ATTN_BACKEND="${TAHI_VLLM_ATTN_BACKEND:-}"
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --model)
      MODEL="$2"
      shift 2
      ;;
    --port)
      PORT="$2"
      shift 2
      ;;
    --quantization)
      QUANTIZATION="$2"
      shift 2
      ;;
    --max-model-len)
      MAX_MODEL_LEN="$2"
      shift 2
      ;;
    --tensor-parallel-size)
      TP_SIZE="$2"
      shift 2
      ;;
    --attention-backend)
      ATTN_BACKEND="$2"
      shift 2
      ;;
    *)
      EXTRA_ARGS+=("$1")
      shift
      ;;
  esac
done

if [[ -n "$QUANTIZATION" ]]; then
  EXTRA_ARGS+=("--quantization" "$QUANTIZATION")
fi

# Refuse to start on top of an existing server. Two vLLM instances on one GPU
# means the second either OOMs or silently gets a starved KV cache -- and a
# starved cache shows up later as mysterious latency, not as an error here.
if pgrep -f "vllm.entrypoints.openai.api_server" >/dev/null 2>&1; then
  echo "ERROR: a vLLM server is already running." >&2
  echo "       Stop it first:  pkill -f vllm.entrypoints.openai.api_server" >&2
  exit 1
fi

# Common workarounds for vLLM v1 engine / flashinfer / attention backend issues.
# vLLM v1 (default in 0.6.4+) is fast but crashy on many DGX configs; force v0.
export VLLM_USE_V1=${VLLM_USE_V1:-0}
export FLASHINFER_DISABLE_VERSION_CHECK=${FLASHINFER_DISABLE_VERSION_CHECK:-1}
if [[ -n "$ATTN_BACKEND" ]]; then
  export VLLM_ATTENTION_BACKEND="$ATTN_BACKEND"
fi

# vLLM preallocates a KV-cache arena at startup and holds it for the process
# lifetime -- by default 0.90 of VRAM. That is fine when vLLM owns the GPU, but
# Level 3 native work runs PyTorch in-process on the SAME device, and it gets
# whatever vLLM did not reserve. Cap vLLM here rather than letting the native
# side fail and silently drop to CPU.
#
#   GCCA adapter footprint (fp32, the amount that must fit alongside vLLM):
#     d_model=768   ->    14 MB
#     d_model=8192  ->  1124 MB   (Qwen-72B hidden size)
#
# 0.75 leaves ~32 GB on a 130 GB GB10 for in-process adapters and activations.
# Raise it toward 0.90 when vLLM owns the GPU alone.
GPU_MEM_UTIL=${GPU_MEM_UTIL:-0.75}

cat <<BANNER
────────────────────────────────────────────────────────────────────
 TAHI vLLM server
────────────────────────────────────────────────────────────────────
  model            ${MODEL}
  quantization     ${QUANTIZATION:-none}
  port             ${PORT}
  max-model-len    ${MAX_MODEL_LEN}
  tensor-parallel  ${TP_SIZE}
  gpu-mem-util     ${GPU_MEM_UTIL}   (leaves room for in-process adapters)

  Point TAHI at it in another shell:

    export TAHI_LLM_PROVIDER=vllm
    export VLLM_BASE_URL=http://localhost:${PORT}/v1
    export TAHI_LLM_MODEL=${MODEL}
    export TAHI_STRICT=1

  Then:  PYTHONPATH=src python benchmarks/run_enterprise_rag.py --self-test
────────────────────────────────────────────────────────────────────
BANNER

# Write the client-side env to a file so it can be sourced instead of retyped.
ENV_FILE="$(dirname "$0")/../.tahi-vllm.env"
cat > "$ENV_FILE" <<ENVFILE
# Generated by start_vllm_server.sh -- source this to point TAHI at the server.
export TAHI_LLM_PROVIDER=vllm
export VLLM_BASE_URL=http://localhost:${PORT}/v1
export TAHI_LLM_MODEL=${MODEL}
export VLLM_API_KEY=not-needed
export TAHI_STRICT=1
ENVFILE
echo "Wrote client env to ${ENV_FILE}  (source it: . .tahi-vllm.env)"
echo

set -x
exec python -m vllm.entrypoints.openai.api_server \
  --model "$MODEL" \
  --tensor-parallel-size "$TP_SIZE" \
  --max-model-len "$MAX_MODEL_LEN" \
  --gpu-memory-utilization "$GPU_MEM_UTIL" \
  --port "$PORT" \
  "${EXTRA_ARGS[@]}"
